import Headbar from "@/components/Content/Headbar/Headbar";
import Navbar from "@/components/Navbar";
import SocialSidebar from "@/components/SocialSidebar";
import { chillPixel } from "@/font/font";
import { Box, Stack, Typography } from "@mui/material";
import Head from "next/head";
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
          <Stack spacing={3} width="100%">
            <Headbar />
          </Stack>
          <SocialSidebar />
      </main>
    </>
  );
}
